name: Basic build test for pull request.


on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: "stable"
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub upgrade
      - run: flutter build apk --no-tree-shake-icons
  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/ios/iphoneos/app.ipa"
          tag: v0.1.${{ github.run_number }}

